### ISSUE TITLE
questions about precision, recall and threshold interval

### ISSUE THREAD

**Issue by seonhoon1002** [Abyssaledge/Extensible-Object-Detection-Evaluator#1]
Thank you for sharing the evaluation codes. 
But I have some questions.
1. Do "Precision and Recall" in your code mean "AP and AR"?
2. If '1' is right, can I ask "threshold interval" for measuring AP and AR?
3.  What is the means of 'crowd'?
Thanks : )

**Comment by Abyssaledge** [comment]
1. yes
2. What do you mean "threshold interval"? like IoU@0.5:0.05:0.9?
3. if the distance between any two objects is less than a certain threshold, they are crowded objects.

**Comment by seonhoon1002** [comment]
2 --> "threshold interval" means interval for average precision such as "AP@11, AP@40" in KITTI : )

**Comment by Abyssaledge** [comment]
See https://github.com/Abyssaledge/Extensible-Object-Detection-Evaluator/blob/main/od_evaluation/params.py#L68

**Comment by seonhoon1002** [comment]
Ok. I see
Thanks!
