### ISSUE TITLE
overall performance in Cyclist

### ISSUE THREAD

**Issue by seonhoon1002** [Abyssaledge/Extensible-Object-Detection-Evaluator#2]
Hello, I have a question about evaluation value in Cyclist
I run your code and I got the overall performance of "Vehicle, Pedestrian, Cyclist":
├── Precision
│   ├── IoU@0.5
│   │   ├── type_Cyclist
│   │   │   ├── range_OVERALL: 72.2558
│   │   │   ├── range_[0, 30]: 87.0509
│   │   │   ├── range_[30, 50]: 68.8192
│   │   │   └── range_[50, 80]: 57.4541
│   │   ├── type_Pedestrian
│   │   │   ├── range_OVERALL: 71.6198
│   │   │   ├── range_[0, 30]: 80.6509
│   │   │   ├── range_[30, 50]: 71.5409
│   │   │   └── range_[50, 80]: 55.4812
│   ├── IoU@0.7
│   │   └── type_Vehicle
│   │       ├── range_OVERALL: 63.7904
│   │       ├── range_[0, 30]: 88.8468
│   │       ├── range_[30, 50]: 63.9025
│   │       └── range_[50, 80]: 35.9553

And bellows are values evaluated by Waymo official code(Level2 mAP):
Vehicle@0.7: 63.79
Pedestrian@0.5: 71.50
Cyclist@0.5: 68.55

So I think Pedestrian and Vehicle reimplement well if overall means official Waymo L2 overall metric, but Cyclist has a different value 

Can I ask that when you evaluate the Cyclist by this code, do you happen to like my case?

**Comment by Abyssaledge** [comment]
I adopt the same coding logic for each class, so I believe the results of Cyclist are right. The difference might be caused by the limited number of cyclist instances in WOD.  I calculate the area under the PR-curve in COCO-style instead of the one in Waymo, so I guess there might be some differences for some rare classes.

**Comment by seonhoon1002** [comment]
Aha, I understood.
And I'm sorry for taking your time, but can I ask one more question?
There is [12, +∞] in Table 2 in your new paper(FSD). how did you make that setting?  
Just set the range parameter like "[12,100000]" or modify your code to remove the upper bound.

**Comment by Abyssaledge** [comment]
Yes, you can use a large upper bound to achieve this.

**Comment by seonhoon1002** [comment]
Ok, I'll try that way 
Thanks.
